import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../components/Navbar";
import { Montserrat } from "next/font/google";
import FooterPage from "@/components/Footer";

const montserrat = Montserrat({
  weight: "500",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Єпомічник",
  description: "Generated by Ihor",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`min-h-screen flex flex-col justify-between bg-gradient-to-b from-gray-100 to-gray-300 ${montserrat.className}`}
      >
        <div>
          <Navbar />
          {children}
        </div>
        <FooterPage />
      </body>
    </html>
  );
}
